version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.Express  
    ports:
      - "8080:8080"
    restart: always

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.React
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend-network

networks:
  backend-network:

